services:
  postgres:
    image: postgres:17
    container_name: astrail-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c timezone=Asia/Ho_Chi_Minh -c log_timezone=Asia/Ho_Chi_Minh
    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  identity-service:
    build:
      context: ./src/services/identity-service
      dockerfile: Dockerfile
    container_name: astrail-identity-service
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/astrail
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  user-service:
    build:
      context: ./src/services/user-service
      dockerfile: Dockerfile
    container_name: astrail-user-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - identity-service
    environment:
      AUTH_SERVER_JWK_URI: http://identity-service:9000/api/auth/jwks
      AUTH_SERVER_ISSUER_URI: http://localhost:9000

  api-gateway:
    build:
      context: ./src/services/api-gateway
      dockerfile: Dockerfile
    container_name: astrail-api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - identity-service
      - user-service
    environment:
      AUTH_SERVER_AUTH_URI: http://localhost:9000/api/auth/authorize
      AUTH_SERVER_TOKEN_URI: http://identity-service:9000/api/auth/token
      AUTH_SERVER_JWK_URI: http://identity-service:9000/api/auth/jwks
      AUTH_SERVER_USERINFO_URI: http://identity-service:9000/api/auth/userinfo
      USER_SERVICE_URL: http://user-service:8081
      IDENTITY_SERVICE_URL: http://identity-service:9000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}


  web-app:
    build:
      context: ./src/web-app/astrail
      dockerfile: Dockerfile
    container_name: astrail-web-app
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - api-gateway

volumes:
  postgres_data: