services:
  postgres:
    image: postgres:17
    container_name: astrail-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c timezone=Asia/Ho_Chi_Minh -c log_timezone=Asia/Ho_Chi_Minh
    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  identity-service:
    build:
      context: ./src/services/identity-service
      dockerfile: Dockerfile
    container_name: astrail-identity-service
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/astrail
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web-app:
    build:
      context: ./src/web-app/astrail
      dockerfile: Dockerfile
    container_name: astrail-web-app
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - identity-service

volumes:
  postgres_data: